---
title: "A Study on Penguins: A Minimal Reproducible Example"
author:
  - name: "Josephine Zerna"
    orcid: 0000-0003-2892-884X
    roles:
      - conceptualization
      - writing
    affiliations:
      - id: "tu-dresden"
        name: "Technische Universität Dresden"
        group: Chair of Differential and Personality Psychology
        department: Faculty of Psychology
        city: Dresden
        postal-code: 01069
  - name: "Christoph Scheffel"
    affiliation:
      - id: "tu-dresden"
    email: "christoph_scheffel@tu-dresden.de"
    orcid: 0000-0001-5963-9229
    corresponding: true
    roles:
      - project administration
      - methodology
date: "today"
lang: en
abstract: "This document is a minimal, reproducible manuscript using the penguins data set as an example."
keywords: [penguins, reproducibility, minimal, example]
bibliography: Bibliography.bib
format:
  pdf:
    pdf-engine: lualatex
    documentclass: scrartcl
    papersize: a4
---

# Introduction

Penguins are fascinating creatures that inhabit various regions of the Southern Hemisphere, including Antarctica and surrounding islands.
The study of penguins provides valuable insights into ecosystem dynamics, climate change impacts, and evolutionary biology [@smith2020; @jones2018].

<!-- ADD IMAGE HERE -->

This manuscript presents a minimal reproducible example utilizing the penguins data set to demonstrate scientific workflows in R.
<!-- CITE DATA HERE -->

# Methods

We conducted a Welch two-sample *t*-test to compare the average bill lengths between male and female penguins.
The null hypothesis ($H_0$) states that there is no difference in bill lengths between male and female penguins, while the alternative hypothesis ($H_1$) suggests a significant difference.

The *t*-test was performed using the `t.test()` function in R, with a significance level of 0.05.

# Results

# Discussion

The significant difference in bill lengths between male and female penguins suggests potential sexual dimorphism in this trait.
This finding aligns with previous research indicating differential foraging strategies and resource partitioning between male and female penguins [@brown2015; @wilson2019].

Understanding the factors influencing bill morphology in penguins is crucial for conservation efforts and ecosystem management, particularly in the face of ongoing environmental challenges.

# References

::: {#refs}
:::